/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CapillaJesusDelRio.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CapillaJesusDelRio(props) {
  const { nodes, materials } = useGLTF('./models/CapillaJesusDelRio.glb')
  return (
    <group {...props} dispose={null} scale={0.5}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.301}>
        <mesh  geometry={nodes.Mesh.geometry} material={materials.Piedra___Caliza_Fina} />
        <mesh  geometry={nodes.Mesh_1.geometry} material={materials.Pintura__Cadmio_Naranja} />
        <mesh  geometry={nodes.Mesh_2.geometry} material={materials.FrontColor} />
        <mesh  geometry={nodes.Mesh_3.geometry} material={materials._Tile_Limestone_Large_1} />
        <mesh  geometry={nodes.Mesh_4.geometry} material={materials.muro_ladrillo_crema} />
        <mesh  geometry={nodes.Mesh_5.geometry} material={materials.Blacktop_Old_02} />
        <mesh  geometry={nodes.Mesh_6.geometry} material={materials.Ladrillo___Aparejo_Com_n} />
        <mesh  geometry={nodes.Mesh_7.geometry} material={materials.Asphalt_New} />
        <mesh  geometry={nodes.Mesh_8.geometry} material={materials.Ladrillo___A_Espiga_Rojo} />
        <mesh  geometry={nodes.Mesh_9.geometry} material={materials.Color_M08} />
        <mesh  geometry={nodes.Mesh_10.geometry} material={materials.Wood_Floor} />
        <mesh  geometry={nodes.Mesh_11.geometry} material={materials.Aluminum} />
        <mesh  geometry={nodes.Mesh_12.geometry} material={materials.Hormig_n___Oscuro_24} />
        <mesh  geometry={nodes.Mesh_13.geometry} material={materials.Marble_Carrara_Gold_Floor_Tile} />
        <mesh  geometry={nodes.Mesh_14.geometry} material={materials.TABLONES} />
        <mesh  geometry={nodes.Mesh_15.geometry} material={materials.Translucent_Resin_Crush_Gray} />
        <mesh  geometry={nodes.Mesh_16.geometry} material={materials.Impermeabilizante} />
        <mesh  geometry={nodes.Mesh_17.geometry} material={materials.Translucent_Glass_Sky_Reflection} />
        <mesh  geometry={nodes.Mesh_18.geometry} material={materials.muro_sin_ac} />
        <mesh  geometry={nodes.Mesh_19.geometry} material={materials.ladrillo_espiga1_1} />
        <mesh  geometry={nodes.Mesh_20.geometry} material={materials.ladrillo_espiga1} />
        <mesh  geometry={nodes.Mesh_21.geometry} material={materials._Charcoal_1} />
        <mesh  geometry={nodes.Mesh_22.geometry} material={materials.M_0136_Charcoal} />
        <mesh  geometry={nodes.Mesh_23.geometry} material={materials.Brick_Antique_02} />
        <mesh  geometry={nodes.Mesh_24.geometry} material={materials._Tile_Hexagon_White_1} />
        <mesh  geometry={nodes.Mesh_25.geometry} material={materials.Rough_Square_Concrete_Block} />
        <mesh  geometry={nodes.Mesh_26.geometry} material={materials.Terracotta__Hexagonal} />
        <mesh  geometry={nodes.Mesh_27.geometry} material={materials.Color_000} />
        <mesh  geometry={nodes.Mesh_28.geometry} material={materials._1} />
        <mesh  geometry={nodes.Mesh_29.geometry} material={materials.Stone_Pavers_Flagstone_Gray} />
        <mesh  geometry={nodes.Mesh_30.geometry} material={materials._Stone_Brushed_Khaki_2} />
        <mesh  geometry={nodes.Mesh_31.geometry} material={materials._2} />
        <mesh  geometry={nodes.Mesh_32.geometry} material={materials.Stone_Vein_Gray} />
        <mesh  geometry={nodes.Mesh_33.geometry} material={materials._3} />
        <mesh  geometry={nodes.Mesh_34.geometry} material={materials.M_0137_Black} />
        <mesh  geometry={nodes.Mesh_35.geometry} material={materials.M_0130_Gainsboro} />
      </group>
      <mesh geometry={nodes.muroLogos.geometry} material={materials.M_muroLogos} position={[0.53, 0.17, -5.664]} />
      <mesh geometry={nodes.pisoConInfo.geometry} material={materials['capillaJesus del rio']} />
    </group>
  )
}

useGLTF.preload('./models/CapillaJesusDelRio.glb')
