/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../public/models/CapillaJesusDelRio.glb ./ 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CapillaJesusDelRio.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.logos_F.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.Mesh002.geometry} material={materials['Piedra___Caliza_Fina.001']} />
      <mesh geometry={nodes.Mesh002_1.geometry} material={materials['Pintura__Cadmio_Naranja.001']} />
      <mesh geometry={nodes.Mesh002_2.geometry} material={materials['FrontColor.001']} />
      <mesh geometry={nodes.Mesh002_3.geometry} material={materials['_Tile_Limestone_Large_1.001']} />
      <mesh geometry={nodes.Mesh002_4.geometry} material={materials['muro_ladrillo_crema.001']} />
      <mesh geometry={nodes.Mesh002_5.geometry} material={materials['Blacktop_Old_02.001']} />
      <mesh geometry={nodes.Mesh002_6.geometry} material={materials['Ladrillo___Aparejo_Com_n.001']} />
      <mesh geometry={nodes.Mesh002_7.geometry} material={materials['Asphalt_New.001']} />
      <mesh geometry={nodes.Mesh002_8.geometry} material={materials['Ladrillo___A_Espiga_Rojo.001']} />
      <mesh geometry={nodes.Mesh002_9.geometry} material={materials['Color_M08.001']} />
      <mesh geometry={nodes.Mesh002_10.geometry} material={materials['Wood_Floor.001']} />
      <mesh geometry={nodes.Mesh002_11.geometry} material={materials['Aluminum.001']} />
      <mesh geometry={nodes.Mesh002_12.geometry} material={materials['Hormig_n___Oscuro_24.001']} />
      <mesh geometry={nodes.Mesh002_13.geometry} material={materials['Marble_Carrara_Gold_Floor_Tile.001']} />
      <mesh geometry={nodes.Mesh002_14.geometry} material={materials['TABLONES.001']} />
      <mesh geometry={nodes.Mesh002_15.geometry} material={materials['Translucent_Resin_Crush_Gray.001']} />
      <mesh geometry={nodes.Mesh002_16.geometry} material={materials['Impermeabilizante.001']} />
      <mesh geometry={nodes.Mesh002_17.geometry} material={materials['Translucent_Glass_Sky_Reflection.001']} />
      <mesh geometry={nodes.Mesh002_18.geometry} material={materials['muro_sin_ac.001']} />
      <mesh geometry={nodes.Mesh002_19.geometry} material={materials['ladrillo_espiga1_1.001']} />
      <mesh geometry={nodes.Mesh002_20.geometry} material={materials['ladrillo_espiga1.001']} />
      <mesh geometry={nodes.Mesh002_21.geometry} material={materials['_Charcoal_1.001']} />
      <mesh geometry={nodes.Mesh002_22.geometry} material={materials['M_0136_Charcoal.001']} />
      <mesh geometry={nodes.Mesh002_23.geometry} material={materials['Brick_Antique_02.001']} />
      <mesh geometry={nodes.Mesh002_24.geometry} material={materials['_Tile_Hexagon_White_1.001']} />
      <mesh geometry={nodes.Mesh002_25.geometry} material={materials['Rough_Square_Concrete_Block.001']} />
      <mesh geometry={nodes.Mesh002_26.geometry} material={materials['Terracotta__Hexagonal.001']} />
      <mesh geometry={nodes.Mesh002_27.geometry} material={materials['Color_000.001']} />
      <mesh geometry={nodes.Mesh002_28.geometry} material={materials['_1.001']} />
      <mesh geometry={nodes.Mesh002_29.geometry} material={materials['Stone_Pavers_Flagstone_Gray.001']} />
      <mesh geometry={nodes.Mesh002_30.geometry} material={materials['_Stone_Brushed_Khaki_2.001']} />
      <mesh geometry={nodes.Mesh002_31.geometry} material={nodes.Mesh002_31.material} />
      <mesh geometry={nodes.Mesh002_32.geometry} material={materials['Stone_Vein_Gray.001']} />
      <mesh geometry={nodes.Mesh002_33.geometry} material={materials['M_0137_Black.001']} />
      <mesh geometry={nodes.Mesh002_34.geometry} material={materials['M_0130_Gainsboro.001']} />
    </group>
  )
}

useGLTF.preload('/CapillaJesusDelRio.glb')
