/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../public/models/exConventoSF.glb ./ 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ExSanFrancisco(props) {
  const { nodes, materials } = useGLTF('./models/exConventoSF.glb')
  return (
    <group {...props} dispose={null} >
      <group position={[1.792, 0, -4.491]} rotation={[Math.PI / 2, 0, -0.315]} scale={0.103}>
        <mesh geometry={nodes.Mesh.geometry} material={materials._15} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials._11} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.Concrete__Crazy_Paving} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials.Granite_Light_Gray} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials.Shou_Sugi_Ban__Yakisugi_} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials.Color_M08} />
        <mesh geometry={nodes.Mesh_6.geometry} material={materials.Wood_Floor} />
        <mesh geometry={nodes.Mesh_7.geometry} material={materials.Aluminum} />
        <mesh geometry={nodes.Mesh_8.geometry} material={materials.Wood_Veneer_01} />
        <mesh geometry={nodes.Mesh_9.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh_10.geometry} material={materials.Embossed_Plaster} />
        <mesh geometry={nodes.Mesh_11.geometry} material={materials._14} />
        <mesh geometry={nodes.Mesh_12.geometry} material={materials.Ash_Heartwood_Veneer_Staggered} />
        <mesh geometry={nodes.Mesh_13.geometry} material={materials._1} />
        <mesh geometry={nodes.Mesh_14.geometry} material={materials.Color_D03} />
        <mesh geometry={nodes.Mesh_15.geometry} material={materials.Color_M00} />
        <mesh geometry={nodes.Mesh_16.geometry} material={materials._Color_M01_1} />
        <mesh geometry={nodes.Mesh_17.geometry} material={materials.Translucent_Glass_Blue} />
        <mesh geometry={nodes.Mesh_18.geometry} material={materials._6} />
        <mesh geometry={nodes.Mesh_19.geometry} material={materials.Sandstone} />
        <mesh geometry={nodes.Mesh_20.geometry} material={materials.Granite_Brown} />
        <mesh geometry={nodes.Mesh_21.geometry} material={materials.Granite} />
        <mesh geometry={nodes.Mesh_22.geometry} material={materials.Polished_Concrete_none_bme4ob} />
        <mesh geometry={nodes.Mesh_23.geometry} material={materials.Dark_Grey} />
        <mesh geometry={nodes.Mesh_24.geometry} material={materials.Translucent_Glass_Sky_Reflection} />
        <mesh geometry={nodes.Mesh_25.geometry} material={materials.Western_Red_Cedar} />
        <mesh geometry={nodes.Mesh_26.geometry} material={materials._CorrogateShiny_3} />
        <mesh geometry={nodes.Mesh_27.geometry} material={materials.Granite__Crazy_Paving} />
        <mesh geometry={nodes.Mesh_28.geometry} material={materials._Water_Dark_Blue_1} />
        <mesh geometry={nodes.Mesh_29.geometry} material={materials.Drill_Marked_Granite__Drystone} />
        <mesh geometry={nodes.Mesh_30.geometry} material={materials._4} />
        <mesh geometry={nodes.Mesh_31.geometry} material={materials.Translucent_Glass_Gray} />
        <mesh geometry={nodes.Mesh_32.geometry} material={materials._7} />
        <mesh geometry={nodes.Mesh_33.geometry} material={materials.Flagstone__Rounded_Rubble} />
        <mesh geometry={nodes.Mesh_34.geometry} material={materials.Polished_Concrete} />
        <mesh geometry={nodes.Mesh_35.geometry} material={materials.Zinc} />
        <mesh geometry={nodes.Mesh_36.geometry} material={materials._13} />
        <mesh geometry={nodes.Mesh_37.geometry} material={materials._10} />
        <mesh geometry={nodes.Mesh_38.geometry} material={materials._9} />
        <mesh geometry={nodes.Mesh_39.geometry} material={materials._12} />
        <mesh geometry={nodes.Mesh_40.geometry} material={materials.CMU_Block} />
        <mesh geometry={nodes.Mesh_41.geometry} material={materials.Granite_none_vwl4pw} />
        <mesh geometry={nodes.Mesh_42.geometry} material={materials.Shadowplay_Craft__Split_Modular} />
        <mesh geometry={nodes.Mesh_43.geometry} material={materials.Granito_osc} />
        <mesh geometry={nodes.Mesh_44.geometry} material={materials.Oak} />
        <mesh geometry={nodes.Mesh_45.geometry} material={materials.Wood_Bamboo_Medium} />
        <mesh geometry={nodes.Mesh_46.geometry} material={materials.M_03___Default1} />
        <mesh geometry={nodes.Mesh_47.geometry} material={materials.AM113_059_Staphyella_pinnata} />
        <mesh geometry={nodes.Mesh_48.geometry} material={materials.Limestone__Corfiot} />
        <mesh geometry={nodes.Mesh_49.geometry} material={materials.Bembridge_Antique__Staggered} />
        <mesh geometry={nodes.Mesh_50.geometry} material={materials.Mondo_Grass} />
        <mesh geometry={nodes.Mesh_51.geometry} material={materials.Limestone_none_03m8nq} />
        <mesh geometry={nodes.Mesh_52.geometry} material={materials.Even_Drag_Brick__1_3_Stretcher} />
        <mesh geometry={nodes.Mesh_53.geometry} material={materials.Even_Drag_Brick__1_3_Stretcher1} />
        <mesh geometry={nodes.Mesh_54.geometry} material={materials.Even_Drag_Brick__1_3_Stretcher2} />
        <mesh geometry={nodes.Mesh_55.geometry} material={materials.Even_Drag_Brick__1_3_Stretcher3} />
        <mesh geometry={nodes.Mesh_56.geometry} material={materials.Even_Drag_Brick__1_3_Stretcher4} />
        <mesh geometry={nodes.Mesh_57.geometry} material={materials.Even_Drag_Brick__1_3_Stretcher5} />
        <mesh geometry={nodes.Mesh_58.geometry} material={materials.Even_Drag_Brick__1_3_Stretcher6} />
        <mesh geometry={nodes.Mesh_59.geometry} material={materials.Even_Drag_Brick__1_3_Stretcher7} />
        <mesh geometry={nodes.Mesh_60.geometry} material={materials.Even_Drag_Brick__1_3_Stretcher8} />
        <mesh geometry={nodes.Mesh_61.geometry} material={materials.Even_Drag_Brick__1_3_Stretcher9} />
        <mesh geometry={nodes.Mesh_62.geometry} material={materials.Even_Drag_Brick__1_3_Stretcher10} />
        <mesh geometry={nodes.Mesh_63.geometry} material={materials.Granite_none_8roqd2} />
        <mesh geometry={nodes.Mesh_64.geometry} material={materials.Even_Drag_Brick_Stretcher} />
        <mesh geometry={nodes.Mesh_65.geometry} material={materials.Granite_none_cf3v6l} />
        <mesh geometry={nodes.Mesh_66.geometry} material={materials._} />
        <mesh geometry={nodes.Mesh_67.geometry} material={materials.MADERA_OSC} />
        <mesh geometry={nodes.Mesh_68.geometry} material={materials._2} />
        <mesh geometry={nodes.Mesh_69.geometry} material={materials.Embossed_Plaster_none_lqbyph} />
        <mesh geometry={nodes.Mesh_70.geometry} material={materials.Limestone1} />
        <mesh geometry={nodes.Mesh_71.geometry} material={materials.Stone_Brushed_Khaki} />
      </group>
      <mesh geometry={nodes.pisoLogos.geometry} material={materials.M_muroLogos} position={[1.33, 0.032, 4.093]} rotation={[Math.PI / 2, 0, 3.106]} scale={1.714} />
      {/* <mesh geometry={nodes.pisoInfo.geometry} material={materials.capillaJesus_del_rio} position={[1.33, 0.032, 4.093]} rotation={[Math.PI / 2, 0, 3.106]} scale={1.714} /> */}
    </group>
  )
}

useGLTF.preload('./models/exConventoSF.glb')
