/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../public/models/IglesiaDelBuenVecino.glb ./ 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/IglesiaDelBuenVecino.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.logos_F.geometry} material={materials.lambert2} position={[-0.07, -0.381, -0.699]} rotation={[Math.PI / 2, 0, 0]} scale={1.068} />
      <group position={[-0.353, 0.093, 5.926]} rotation={[Math.PI / 2, 0, -1.574]} scale={0.003}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials['Baldosas - Tostado 30x30']} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials['Estuco - Blanco Fino']} />
        <mesh geometry={nodes.Mesh003_2.geometry} material={materials['Estuco - Blanco Rugoso']} />
        <mesh geometry={nodes.Mesh003_3.geometry} material={materials['Estuco - Rojo Rugoso']} />
        <mesh geometry={nodes.Mesh003_4.geometry} material={materials.GDLM26_bark01} />
        <mesh geometry={nodes.Mesh003_5.geometry} material={materials.GDLM27_leafs1} />
        <mesh geometry={nodes.Mesh003_6.geometry} material={materials['Hormigón - 02']} />
        <mesh geometry={nodes.Mesh003_7.geometry} material={materials['Hormigón - 04']} />
        <mesh geometry={nodes.Mesh003_8.geometry} material={materials['Hormigón - 10']} />
        <mesh geometry={nodes.Mesh003_9.geometry} material={materials['Ladrillo - Aparejo Corrido']} />
        <mesh geometry={nodes.Mesh003_10.geometry} material={materials['Madera - Caoba Horizontal']} />
        <mesh geometry={nodes.Mesh003_11.geometry} material={materials['Metal - Hierro']} />
        <mesh geometry={nodes.Mesh003_12.geometry} material={materials['Pintura- Arena Beige']} />
        <mesh geometry={nodes.Mesh003_13.geometry} material={materials['Pintura- Arena Beige (1)']} />
        <mesh geometry={nodes.Mesh003_14.geometry} material={materials['Pintura- Azul Pálido']} />
        <mesh geometry={nodes.Mesh003_15.geometry} material={materials['Pintura- Blanco Satinado']} />
        <mesh geometry={nodes.Mesh003_16.geometry} material={materials['Pintura- Burdeos']} />
        <mesh geometry={nodes.Mesh003_17.geometry} material={materials['Pintura- Gris Claro']} />
        <mesh geometry={nodes.Mesh003_18.geometry} material={materials['Pintura- Gris Oscuro']} />
        <mesh geometry={nodes.Mesh003_19.geometry} material={materials['Pintura- Oroen Ocre']} />
        <mesh geometry={nodes.Mesh003_20.geometry} material={materials['Pintura- Titanio Blanco']} />
        <mesh geometry={nodes.Mesh003_21.geometry} material={materials['Tierra - Marrón']} />
        <mesh geometry={nodes.Mesh003_22.geometry} material={materials['Vidrio - Claro Rápido']} />
      </group>
    </group>
  )
}

useGLTF.preload('/IglesiaDelBuenVecino.glb')
