/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../public/models/IglesiaSnNicolasTolentino.glb ./ 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/IglesiaSnNicolasTolentino.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.logos_F.geometry} material={materials.lambert2} position={[1.084, -0.01, -1.443]} rotation={[Math.PI / 2, 0, 0]} scale={1.068} />
      <group position={[-1.89, 0.606, -1.861]} rotation={[Math.PI / 2, 0, 1.675]} scale={0.309}>
        <mesh geometry={nodes.Mesh004.geometry} material={materials._Metal_Corrogated_Shiny_1} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={materials.Color_D08} />
        <mesh geometry={nodes.Mesh004_2.geometry} material={materials.Dark_Oak} />
        <mesh geometry={nodes.Mesh004_3.geometry} material={materials._Brick_Rough_Dark_1} />
        <mesh geometry={nodes.Mesh004_4.geometry} material={materials.Pierre_JJ} />
        <mesh geometry={nodes.Mesh004_5.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh004_6.geometry} material={materials._Roofing_Metal_Standing_Seam_Red_1} />
        <mesh geometry={nodes.Mesh004_7.geometry} material={materials.SaddleBrown1} />
        <mesh geometry={nodes.Mesh004_8.geometry} material={materials._Metal_Seamed_3} />
        <mesh geometry={nodes.Mesh004_9.geometry} material={materials._16} />
        <mesh geometry={nodes.Mesh004_10.geometry} material={materials._Charcoal_2} />
        <mesh geometry={nodes.Mesh004_11.geometry} material={materials._Stone_Masonry_Multi_1} />
        <mesh geometry={nodes.Mesh004_12.geometry} material={materials._Stone_Sandstone_Ashlar_Light_3} />
        <mesh geometry={nodes.Mesh004_13.geometry} material={materials.Stone_Sandstone_Ashlar_Light} />
        <mesh geometry={nodes.Mesh004_14.geometry} material={materials._Metal_Seamed_1} />
        <mesh geometry={nodes.Mesh004_15.geometry} material={materials._Color_D02_1} />
        <mesh geometry={nodes.Mesh004_16.geometry} material={materials._22} />
        <mesh geometry={nodes.Mesh004_17.geometry} material={materials.Stone_Flagstone_Ashlar} />
        <mesh geometry={nodes.Mesh004_18.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Mesh004_19.geometry} material={materials.Asphalt_New} />
        <mesh geometry={nodes.Mesh004_20.geometry} material={materials._0136_Charcoal_1} />
        <mesh geometry={nodes.Mesh004_21.geometry} material={materials._Translucent_Glass_Gray_1} />
        <mesh geometry={nodes.Mesh004_22.geometry} material={materials._Charcoal_3} />
        <mesh geometry={nodes.Mesh004_23.geometry} material={materials._Gainsboro_} />
        <mesh geometry={nodes.Mesh004_24.geometry} material={materials.Roofing_Metal_Standing_Seam_Red} />
        <mesh geometry={nodes.Mesh004_25.geometry} material={materials._Color_D02_2} />
        <mesh geometry={nodes.Mesh004_26.geometry} material={materials['Pintura__Gris_Oscuro.001']} />
        <mesh geometry={nodes.Mesh004_27.geometry} material={materials.Color_D16} />
        <mesh geometry={nodes.Mesh004_28.geometry} material={materials.BOI2} />
        <mesh geometry={nodes.Mesh004_29.geometry} material={materials.Blacktop_Old_01} />
        <mesh geometry={nodes.Mesh004_30.geometry} material={materials.Polished_Concrete_Old} />
        <mesh geometry={nodes.Mesh004_31.geometry} material={materials.barandilla} />
        <mesh geometry={nodes.Mesh004_32.geometry} material={materials.Rectangles_Running_4x1} />
        <mesh geometry={nodes.Mesh004_33.geometry} material={materials._Color_000_3} />
        <mesh geometry={nodes.Mesh004_34.geometry} material={materials._White_Square_Tile_1} />
        <mesh geometry={nodes.Mesh004_35.geometry} material={materials.Brick_Tumbled} />
        <mesh geometry={nodes.Mesh004_36.geometry} material={materials.M_0008_LavenderBlush} />
        <mesh geometry={nodes.Mesh004_37.geometry} material={materials._Charcoal_} />
        <mesh geometry={nodes.Mesh004_38.geometry} material={materials.Translucent_Glass_Gray} />
        <mesh geometry={nodes.Mesh004_39.geometry} material={materials._Metal_Seamed_4} />
        <mesh geometry={nodes.Mesh004_40.geometry} material={materials._Color_000_1} />
        <mesh geometry={nodes.Mesh004_41.geometry} material={materials._Concrete_Block_Layers_1} />
        <mesh geometry={nodes.Mesh004_42.geometry} material={materials.Color_F01} />
        <mesh geometry={nodes.Mesh004_43.geometry} material={materials.Tierra1} />
        <mesh geometry={nodes.Mesh004_44.geometry} material={materials.Color_D05} />
        <mesh geometry={nodes.Mesh004_45.geometry} material={materials.Tile_Ceramic_Multi} />
        <mesh geometry={nodes.Mesh004_46.geometry} material={materials.Color_M00} />
        <mesh geometry={nodes.Mesh004_47.geometry} material={materials.Metal_Corrogated_Shiny} />
        <mesh geometry={nodes.Mesh004_48.geometry} material={materials.wood_047_afrormosia_3_b} />
        <mesh geometry={nodes.Mesh004_49.geometry} material={materials.Translucent_Glass_Gray1} />
        <mesh geometry={nodes.Mesh004_50.geometry} material={materials.Ceramic_Tile} />
        <mesh geometry={nodes.Mesh004_51.geometry} material={materials.Wood_Cherry_Original} />
        <mesh geometry={nodes.Mesh004_52.geometry} material={materials.Carpet_Diamond_Yellow} />
        <mesh geometry={nodes.Mesh004_53.geometry} material={materials.M_0136_Charcoal} />
        <mesh geometry={nodes.Mesh004_54.geometry} material={materials.Color_B17} />
        <mesh geometry={nodes.Mesh004_55.geometry} material={materials.Wood_Veneer_01} />
        <mesh geometry={nodes.Mesh004_56.geometry} material={materials.M_0040_Peru} />
        <mesh geometry={nodes.Mesh004_57.geometry} material={materials.Fencing_Chain_Link} />
        <mesh geometry={nodes.Mesh004_58.geometry} material={materials.Granite_Light_Gray} />
        <mesh geometry={nodes.Mesh004_59.geometry} material={materials.Color_A07} />
        <mesh geometry={nodes.Mesh004_60.geometry} material={materials._Stone_Sandstone_Ashlar_Light_1} />
        <mesh geometry={nodes.Mesh004_61.geometry} material={materials._Glass_Gold_Tint_1} />
        <mesh geometry={nodes.Mesh004_62.geometry} material={materials._23} />
        <mesh geometry={nodes.Mesh004_63.geometry} material={materials._4} />
        <mesh geometry={nodes.Mesh004_64.geometry} material={materials._5} />
        <mesh geometry={nodes.Mesh004_65.geometry} material={materials['_6.001']} />
        <mesh geometry={nodes.Mesh004_66.geometry} material={materials._Wood_Bamboo_Medium_2} />
        <mesh geometry={nodes.Mesh004_67.geometry} material={materials.M_129e_43102138_large} />
        <mesh geometry={nodes.Mesh004_68.geometry} material={materials._Metal_Seamed_5} />
        <mesh geometry={nodes.Mesh004_69.geometry} material={materials.Translucent_Glass_Blue} />
        <mesh geometry={nodes.Mesh004_70.geometry} material={materials.Sketchy_Scales} />
        <mesh geometry={nodes.Mesh004_71.geometry} material={materials.Brick_Rough_Dark} />
        <mesh geometry={nodes.Mesh004_72.geometry} material={materials._14} />
        <mesh geometry={nodes.Mesh004_73.geometry} material={materials._15} />
        <mesh geometry={nodes.Mesh004_74.geometry} material={materials.Honeycomb} />
        <mesh geometry={nodes.Mesh004_75.geometry} material={materials.Suede_Brown} />
        <mesh geometry={nodes.Mesh004_76.geometry} material={materials._1} />
        <mesh geometry={nodes.Mesh004_77.geometry} material={materials.Metal_Rough} />
        <mesh geometry={nodes.Mesh004_78.geometry} material={materials._Metal_Seamed_2} />
        <mesh geometry={nodes.Mesh004_79.geometry} material={materials.Translucent_Glass_Safety} />
        <mesh geometry={nodes.Mesh004_80.geometry} material={materials._Color_000_2} />
        <mesh geometry={nodes.Mesh004_81.geometry} material={materials._32} />
        <mesh geometry={nodes.Mesh004_82.geometry} material={materials._Translucent_Glass_Gray_2} />
        <mesh geometry={nodes.Mesh004_83.geometry} material={materials['Tierra.001']} />
        <mesh geometry={nodes.Mesh004_84.geometry} material={materials.Pea_Gravel} />
        <mesh geometry={nodes.Mesh004_85.geometry} material={materials._17} />
        <mesh geometry={nodes.Mesh004_86.geometry} material={materials.brick} />
        <mesh geometry={nodes.Mesh004_87.geometry} material={materials['Estuco___Blanco_Fino.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/IglesiaSnNicolasTolentino.glb')
